### PR TITLE
AWS: install csi driver if k8s >1.23 even if cloud.external=false

### LINKED ISSUE #1814: AWS: pvc block in pending with k8s 1.23 and clould.external=false
<!-- Please use this template if you're reporting a bug. Try to provide as much information as possible. 

If you're reporting a security issue, please check the guidelines for reporting security issues https://github.com/kubermatic/kubeone/blob/master/CONTRIBUTING.md#reporting-a-security-vulnerability

Thanks!
-->

**What happened**:
with k8s `1.23`  when  creating pvc pointing  storageClass with `provisioner: kubernetes.io/aws-ebs`, the pvc stay in pending 
with error `persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator`

**What is the expected behavior**:
pv should be created


**How to reproduce the issue**:
1. create a k8s `1.23.3` cluster on AWS with the following configuration 
  **kubeone.yaml:**
  ```yaml
  apiVersion: kubeone.k8c.io/v1beta2
  kind: KubeOneCluster
  versions:
    kubernetes: '1.23.3'
  cloudProvider:
    aws: {}
  addons:
    enable: true
    addons:
   - name: "default-storage-class"
  ```
2. ensure storage class exist 
  ```bash
  $ k get sc standard-v2 -o yaml          
                                                                                                                                                                                                                                                                                       
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"kubeone.io/addon":"default-storage-class","kubernetes.io/cluster-service":"true"},"name":"standard-v2"},"parameters":{"type":"gp2"},"provisioner":"kubernetes.io/aws-ebs","volumeBindingMode":"WaitForFirstConsumer"}
    storageclass.beta.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2022-02-07T09:17:27Z"
  labels:
    kubeone.io/addon: default-storage-class
    kubernetes.io/cluster-service: "true"
  name: standard-v2
  resourceVersion: "1054"
  uid: f9a76f60-9e79-46e6-854e-6373177a1935
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
  ```
3. create a sts
  ```yaml 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: nginx 
  serviceName: "nginx"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard-v2"
        resources:
          requests:
            storage: 1Gi
  ```

the sts stay in pending state
```bash
 k describe pvc
Name:          www-test-0
Namespace:     default
StorageClass:  standard-v2
Status:        Pending
Volume:
Labels:        app=nginx
Annotations:   volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: ip-172-31-155-79.eu-west-3.compute.internal
               volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       test-0
Events:
  Type    Reason                Age                From                         Message
  ----    ------                ----               ----                         -------
  Normal  WaitForFirstConsumer  19s                persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  ExternalProvisioning  13s (x3 over 19s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
```


**Anything else we need to know?**

**Information about the environment**:
KubeOne version (`kubeone version`): 
```json
{
  "kubeone": {
    "major": "1",
    "minor": "4",
    "gitVersion": "1.4.0-rc.0",
    "gitCommit": "a42407f815ceb762457738b4041823fbb5e1f5a9",
    "gitTreeState": "",
    "buildDate": "2022-02-03T15:28:27Z",
    "goVersion": "go1.17.5",
    "compiler": "gc",
    "platform": "darwin/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "42",
    "gitVersion": "v1.42.4",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```
Operating system: MacOS
Provider you're deploying cluster on: AWS
Operating system you're deploying on: ubuntu

### PR DESCRIPTION
**Pull request by vgramer**
**What this PR does / why we need it**:
since k8s 1.23 `CSIMigrationAWS`  flag is turned on by default and require installation of AWS EBS CSI driver even if we don't use external ccm (kubernetes/kubernetes#106098)

This pr install CSI driver for AWS if `k8S >= 1.23` even if `cloud.external=false`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1814 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
/hold
for discussion

**Review by xmudrii — COMMENTED** [review]
Generally, I'm okay with this change, but I think we should use the same approach for checking the version everywhere. Please see #1808 as an example of how we already implemented the version validation in another place.

File: pkg/addons/ensure.go [hunk 1]
```diff
@@ -106,20 +115,41 @@ func collectAddons(s *state.State) (addonsToDeploy []addonAction) {
...
+				},
+			)
+		} else {
+			// since k8s 1.23 CSIMigrationAWS is turn by default and require installation of AWS EBS CSI driver even if
+			// we don't use external ccm (https://github.com/kubernetes/kubernetes/pull/106098)
+			k8sVersion, err := semver.NewVersion(s.Cluster.Versions.Kubernetes)
+			if err != nil {
+				s.Logger.Warnf("Can not check if k8s version '%s' validate constraint '%s' and therefor if CSI driver must be installed. err=%w", s.Cluster.Versions.Kubernetes, greaterThan23Constraint, err)
+			} else if valid, errs := greaterThan23.Validate(k8sVersion); !valid {
+				s.Logger.Infof("K8s version '%s' does not validate constraint '%s'. Using CSI In-Tree implementation . reasons=%s", s.Cluster.Versions.Kubernetes, greaterThan23Constraint, utilerrors.NewAggregate(errs))
```
Comment (xmudrii) [inline pkg/addons/ensure.go:136]: We don't care about this case at all. I'd ignore it and not print anything.

File: pkg/addons/ensure.go [hunk 2]
```diff
@@ -106,20 +115,41 @@ func collectAddons(s *state.State) (addonsToDeploy []addonAction) {
...
+					name: resources.AddonCCMAws,
+				},
+				addonAction{
+					name: resources.AddonCSIAwsEBS,
+				},
+			)
+		} else {
+			// since k8s 1.23 CSIMigrationAWS is turn by default and require installation of AWS EBS CSI driver even if
+			// we don't use external ccm (https://github.com/kubernetes/kubernetes/pull/106098)
+			k8sVersion, err := semver.NewVersion(s.Cluster.Versions.Kubernetes)
```
Comment (xmudrii) [inline pkg/addons/ensure.go:132]: IMO, we can use `MustParse` instead because validation ensures that it's a valid semver, so this can't fail.

File: pkg/addons/ensure.go [hunk 3]
```diff
@@ -106,20 +115,41 @@ func collectAddons(s *state.State) (addonsToDeploy []addonAction) {
...
+			if err != nil {
+				s.Logger.Warnf("Can not check if k8s version '%s' validate constraint '%s' and therefor if CSI driver must be installed. err=%w", s.Cluster.Versions.Kubernetes, greaterThan23Constraint, err)
+			} else if valid, errs := greaterThan23.Validate(k8sVersion); !valid {
+				s.Logger.Infof("K8s version '%s' does not validate constraint '%s'. Using CSI In-Tree implementation . reasons=%s", s.Cluster.Versions.Kubernetes, greaterThan23Constraint, utilerrors.NewAggregate(errs))
+			} else {
+				s.Logger.Infof("K8s version '%s' validate constraint '%s'. Using CSI driver implementation", s.Cluster.Versions.Kubernetes, greaterThan23Constraint)
```
Comment (xmudrii) [inline pkg/addons/ensure.go:138]: I wouldn't print anything. We already have logs from the addons applier.

**Review by xmudrii — CHANGES_REQUESTED** [review]

File: pkg/addons/ensure.go (hunk 1 above)
Comment (vgramer) [reply pkg/addons/ensure.go]: done :)

File: pkg/addons/ensure.go (hunk 3 above)
Comment (vgramer) [reply pkg/addons/ensure.go]: done :)

**Review by xmudrii — APPROVED** [review]
Thanks, @vgramer!

/lgtm
/approve
