### PR TITLE
Verify that crd.projectcalico.org CRDs established

### LINKED ISSUE #934: Canal CNI defective in rare cases
**What happened**:

When installing a KubeOne cluster, in rare cases the Canal CNI pods are shown to be running but not usable. The entire KubeOne installation fails when deploying the machine-controller in this case. Machine-controller and CoreDNS pods stay in pending state due to the following condition:

`Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "6675d4875be32a0a78d89e208f3fb61d09b72e597e6565ee14121e69336006f8" network for pod "coredns-6955765f44-pggjl": networkPlugin cni failed to set up pod "coredns-6955765f44-pggjl_kube-system" network: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: the server could not find the requested resource (get ClusterInformations.crd.projectcalico.org default), failed to clean up sandbox container "6675d4875be32a0a78d89e208f3fb61d09b72e597e6565ee14121e69336006f8" network for pod "coredns-6955765f44-pggjl": networkPlugin cni failed to teardown pod "coredns-6955765f44-pggjl_kube-system" network: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: the server could not find the requested resource (get ClusterInformations.crd.projectcalico.org default)]`

Canal's calico container logs the following error:

`2020-06-24 11:20:44.067 [ERROR][8] client.go 251: Error creating cluster information config ClusterInformation=&v3.ClusterInformation{TypeMeta:v1.TypeMeta{Kind:"ClusterInformation", APIVersion:"projectcalico.org/v3"}, ObjectMeta:v1.ObjectMeta{Name:"default", GenerateName:"", Namespace:"", SelfLink:"", UID:"4e7c4b94-e00d-437b-959a-e277c807caf7", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0xbfb4eba303d8c464, ext:6639844301, loc:(*time.Location)(0x2d61840)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v3.ClusterInformationSpec{ClusterGUID:"f1988d2388444411b0bd7f42db3471f8", ClusterType:"k8s,canal,kdd", CalicoVersion:"v3.10.0", DatastoreReady:(*bool)(0xc0002b2973)}} error=resource does not exist: ClusterInformation(default) with error: the server could not find the requested resource (post ClusterInformations.crd.projectcalico.org)`

The CRDs in question are available after this. So this looks like a race condition, caused by CRDs not usable yet when the calico container is started. Deleting the canal pods solves the problem.

**What is the expected behavior**:

Maybe separating the CRD deployment and waiting until it is actually available makes the cluster creation more robust.

**How to reproduce the issue**:

Appears occasionally during a `kubeone install`

**Anything else we need to know?**

Might be reinforced by an unresponsive etcd ring due to https://github.com/kubermatic/kubeone/issues/915

**Information about the environment**:
KubeOne version (`kubeone version`): v1.0.0-alpha.6
Operating system: CentOS (master)
Provider you're deploying cluster on: Azure
Operating system you're deploying on: OSX

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
Verify that crd.projectcalico.org CRDs established when using Canal CNI

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #934

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Verify that crd.projectcalico.org CRDs established  when using Canal CNI
```

### CODE REVIEW

File: pkg/clientutil/wait_pods.go [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package clientutil
+
+import (
+	"context"
+
+	"github.com/pkg/errors"
```
Comment (xmudrii) [inline pkg/clientutil/wait_pods.go:22]: Nit: this should go into a dedicated group.

File: pkg/clientutil/crds.go [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package clientutil
+
+import (
+	"context"
+
+	"github.com/pkg/errors"
```
Comment (xmudrii) [inline pkg/clientutil/crds.go:22]: Nit: this should go into a dedicated group.

File: pkg/clientutil/crds.go [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions"
+	dynclient "sigs.k8s.io/controller-runtime/pkg/client"
+)
+
+var (
+	ErrCRDNotEstablished = errors.New("crd is not established")
+)
+
+func VerifyCRD(ctx context.Context, client dynclient.Client, crdName string) (bool, error) {
```
Comment (xmudrii) [inline pkg/clientutil/crds.go:31]: Nit: should we call function `CRDEstablished` or something like that to keep the consistency with other functions (e.g. `PodsReady`)?

File: pkg/templates/machinecontroller/helper.go [hunk 4]
```diff
@@ -20,14 +20,13 @@ import (
 	"context"
 	"time"
 
+	clusterv1alpha1 "github.com/kubermatic/machine-controller/pkg/apis/cluster/v1alpha1"
```
Comment (xmudrii) [inline pkg/templates/machinecontroller/helper.go:23]: Nit: this should go into the kubermatic group.

File: pkg/templates/machinecontroller/helper.go [hunk 5]
```diff
@@ -62,77 +61,51 @@ func WaitReady(s *state.State) error {
...
 	_ = wait.Poll(5*time.Second, 3*time.Minute, func() (bool, error) {
 		lastErr = VerifyCRDs(s)
 		return lastErr == nil, nil
 	})
+
 	return errors.Wrap(lastErr, "failed waiting for CRDs to become ready and established")
 }
 
 // VerifyCRDs verifies are Cluster-API CRDs deployed
 func VerifyCRDs(s *state.State) error {
```
Comment (xmudrii) [inline pkg/templates/machinecontroller/helper.go:91]: I don't like this function's name because it's too similar to `VerifyCRD`.

File: pkg/clientutil/crds.go (hunk 3 above)
Comment (xmudrii) [inline pkg/clientutil/crds.go:31]: Why we don't make this function poll for multiple CRDs (i.e. take a slice of names)? I think this is our most common use case, so it would make sense to have such a function.

File: pkg/clientutil/crds.go [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+			key := dynclient.ObjectKey{Name: gk}
+
+			if err := client.Get(ctx, key, &crd); err != nil {
+				return false, err
+			}
+
+			for _, cond := range crd.Status.Conditions {
+				if cond.Type == apiextensions.Established && cond.Status != apiextensions.ConditionTrue {
+					return false, nil
+				}
```
Comment (xmudrii) [inline pkg/clientutil/crds.go:42]: I was thinking about this approach and I'm not sure that it's safe at all.

This check assumes that the Established condition always exists on the CRD object, but I'm not sure is that true. If `client.Get` returns the result before CRD controller sets the initial conditions, it maybe could happen that `crd.Status.Conditions` don't contain any Established condition. In that case, this check would pass and the function would return true, while the CRD is not Established.

I believe that the following check would be safer

```suggestion
				if cond.Type == apiextensions.Established && cond.Status == apiextensions.ConditionTrue {
					return true, nil
				}
```

It needs some other changes, as well as, it should be tested.

File: pkg/clientutil/wait_pods.go [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+
+	for _, pod := range podsList.Items {
+		if pod.Status.Phase != corev1.PodRunning {
+			return false
+		}
+
+		for _, podcond := range pod.Status.Conditions {
+			if podcond.Type == corev1.PodReady && podcond.Status != corev1.ConditionTrue {
+				return false
+			}
```
Comment (xmudrii) [inline pkg/clientutil/wait_pods.go:56]: Similar to the Established condition, should we check is `ConditionTrue` present and in that case, return true?

File: pkg/clientutil/crds.go (hunk 6 above)
Comment (kron4eg) [reply pkg/clientutil/crds.go:42]: Changing it to such form means introducing a bug. We want to check all of CRDs, but in this form the first found CRD will report positive on behalf of all CRDs under test.

Comment (xmudrii) [reply pkg/clientutil/crds.go:42]: In our case, I believe something like this would work and not introduce a bug:
```go
var found bool
for _, cond := range crd.Status.Conditions {
    if cond.Type == apiextensions.Established && cond.Status == apiextensions.ConditionTrue {
        found = true
        break
    }
}
if !found {
    return false, nil
}
```

Comment (kron4eg) [reply pkg/clientutil/crds.go]: yeah, changed to something similar
