### PR TITLE
Fix APT/RPM PGP key expiration issue for old kubernetes versiosn

### LINKED ISSUE #3460: Issue upgrading Kubernetes cluster from 1.26 to 1.27 due to expired APT keys
I'm experiencing an issue while upgrading my Kubernetes cluster from version 1.26 to 1.27 with KubeOne. The old APT keys required for the upgrade have expired, blocking the process. I see that a fix is available using a new key, as discussed in [kubernetes/release issue #3818](https://github.com/kubernetes/release/issues/3818), but this update hasn’t been integrated into KubeOne yet. Could you please update the key in KubeOne or suggest a workaround?

Thanks for your help!

### PR DESCRIPTION
**Pull request by mohamed-rafraf**
**What this PR does / why we need it**:
This PR addresses the issue of expired GPG keys for Kubernetes apt/rpm repositories by dynamically fetching the GPG key corresponding to the latest stable Kubernetes version.

According to this comment `https://github.com/kubernetes/release/issues/3818#issuecomment-2455160940` 
We can use the gpg key from the latest kubernetes repository.
 
**Which issue(s) this PR fixes**:

Fixes #3460

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Use the GPG key from the latest Kubernetes package repository to fix failures to install older versions of Kubernetes packages
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/scripts/os_amzn.go [hunk 1]
```diff
@@ -44,13 +44,14 @@ echo -n "${yum_proxy}" >> /tmp/yum.conf
 sudo mv /tmp/yum.conf /etc/yum.conf
 
 {{ if .CONFIGURE_REPOSITORIES }}
+LATEST_STABLE=$(curl -s https://cdn.dl.k8s.io/release/stable.txt | sed 's/\.[0-9]*$//')
```
Comment (xmudrii) [inline pkg/scripts/os_amzn.go:47]: Let's not use `cdn.dl.k8s.io` directly, but instead use just `dl.k8s.io`, to be on the safe side.

**Review by xmudrii — CHANGES_REQUESTED** [review]
You also need to update fixtures by running `./hack/update-fixtures.sh`

**Review by xmudrii — APPROVED** [review]
Thank you so much for working on this one!
/lgtm
/approve

**Comment by xmudrii** [comment]
/release-note-edit
```release-note
Use the GPG key from the latest Kubernetes package repository to fix failures to install older versions of Kubernetes packages
```
