### PR TITLE
Use semver constraints on Kubernetes version for upper and lower bounds

### LINKED ISSUE #1807: Fail validation for unsupported newer Kubernetes versions
**What feature would you like to be added?**

KubeOne has an official support matrix for Kubernetes versions available in the docs: https://docs.kubermatic.com/kubeone/v1.3/architecture/compatibility/#supported-kubernetes-versions (for 1.3) and https://docs.kubermatic.com/kubeone/master/architecture/compatibility/#supported-kubernetes-versions (for the upcoming 1.4 release).

We should "codify" that and validate the Kubernetes version in the config file with an "upper limit" version as well. Right now, we only validate that the version isn't too old.

**What are use cases of the feature?**

Prevent deployment of unsupported Kubernetes versions that can break clusters in all sorts of (non-obvious) ways.

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:

This adds validation against two semver constraints that can easily be bumped from the top of the file when adding new Kubernetes versions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1807

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Validate Kubernetes version against supported versions constraints
```

Signed-off-by: Marvin Beckers <marvin@kubermatic.com>

### CODE REVIEW

File: pkg/apis/kubeone/validation/validation.go [hunk 1]
```diff
@@ -253,13 +260,36 @@ func ValidateVersionConfig(version kubeoneapi.VersionConfig, fldPath *field.Path
...
 	}
-	if v.Major() != 1 || v.Minor() < 19 {
-		allErrs = append(allErrs, field.Invalid(fldPath.Child("kubernetes"), version, "kubernetes versions lower than 1.19 are not supported. You need to use an older KubeOne version to upgrade your cluster to v1.19. Please refer to the Compatibility section of docs for more details."))
-	}
+
 	if strings.HasPrefix(version.Kubernetes, "v") {
 		allErrs = append(allErrs, field.Invalid(fldPath.Child("kubernetes"), version, ".versions.kubernetes can't start with a leading 'v'"))
 	}
 
+	lowerConstraint, err := semver.NewConstraint(lowerVersionConstraint)
```
Comment (kron4eg) [inline pkg/apis/kubeone/validation/validation.go:268]: I'd replace this with semver.MustParse or something and saved the result in the package variable. So that later you wouldn't need to return parsing error and check for len(errs) == 0

Comment (embik) [reply pkg/apis/kubeone/validation/validation.go:268]: Good suggestion, thanks!

Comment (embik) [reply pkg/apis/kubeone/validation/validation.go:268]: Although I don't think there is a `MustParse` equivalent for constraints, so maybe this doesn't work.

Comment (kron4eg) [reply pkg/apis/kubeone/validation/validation.go:268]: microscopic wrapper would do it easily

```
func mustParseConstraint(constraint string) *semver.Constraint {
  result, err := semver.ParseConstraint(constraint)
  if err != nil {
    panic(err)
  }
  return result
}
```

Comment (embik) [reply pkg/apis/kubeone/validation/validation.go]: You're of course right, thanks. Added that.

**Review by kron4eg — APPROVED** [review]
/approve

admitting this to 1.4 release

**Comment by xmudrii** [comment]
@kron4eg @embik Do we also want to cherry-pick this to the release/v1.3 branch?

**Comment by kron4eg** [comment]
I'm not sure, most likely no since that would be an unexpected novelty in 1.3.

**Comment by embik** [comment]
I agree with @kron4eg, it's unexpected in a patch release for 1.3. IMHO it should not be cherry-picked. It's "just" codifying the contract we already have in place through the support documentation.
