### PR TITLE
Restart kubelet after containerd

### LINKED ISSUE #1847: Upgrading HA cluster without API server LB is failing because Docker is restarted
**What happened**:

Upgrading an HA cluster that doesn't use LB as an API endpoint is failing because we restart Docker which causes all containers to get terminated. In case the first node is used as an API endpoint, the cluster will be inaccessible until Kubelet detects that containers are terminated. However, that can take several minutes, which is quite long, and will also cause the upgrade process to fail/timeout.

**What is the expected behavior**:

The upgrade process works on HA clusters without an API server LB.

**How to reproduce the issue**:

* Create a cluster on some cloud provider without creating an LB
* Try to upgrade the cluster

**Information about the environment**:
KubeOne version (`kubeone version`): 1.4.0
Provider you're deploying cluster on: Azure
Operating system you're deploying on: Ubuntu

### PR DESCRIPTION
**Pull request by kron4eg**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1847

**Does this PR introduce a user-facing change?**:

```release-note
Restart kubelet after containerd
```

### CODE REVIEW

File: pkg/scripts/render.go [hunk 1]
```diff
@@ -83,6 +83,7 @@ var (
 			{{ template "container-runtime-daemon-config" . }}
 			{{ template "containerd-systemd-setup" . -}}
 			sudo systemctl enable --now docker
+			systemctl status kubelet && sudo systemctl restart kubelet
```
Comment (xmudrii) [inline pkg/scripts/render.go:86]: Why do we need `systemctl status kubelet` here? To check does the service exists?

Comment (kron4eg) [reply pkg/scripts/render.go:86]: Yep, at the time if the initial install kubelet service doesn't exist yet.

**Review by xmudrii — APPROVED** [review]
