### PR TITLE
Error handling refactoring

### LINKED ISSUE #1869: Refactor the error handling
**What feature would you like to be added?**

The errors returned by KubeOne don't tell where's the issue exactly and how to fix it. We need to ensure that errors are descriptive enough, so users know what failed and how to fix it. Also, we should ensure that external tools integrating with KubeOne can more easily parse the errors.

**What are use cases of the feature?**

* https://github.com/kubermatic/kubermatic/issues/8950

### PR DESCRIPTION
**Pull request by kron4eg**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
This PR is only first in series. XRef #1869

**Does this PR introduce a user-facing change?**:

```release-note
Error reporting in CLI now exists with different codes for different error reasons
```

### CODE REVIEW

File: pkg/cmd/kubeconfig.go [hunk 1]
```diff
@@ -38,7 +38,8 @@ func kubeconfigCmd(rootFlags *pflag.FlagSet) *cobra.Command {
 			This command takes KubeOne manifest which contains information about hosts. It's possible to source information about
 			hosts from Terraform output, using the '--tfjson' flag.
 		`),
-		Example: `kubeone kubeconfig -m mycluster.yaml -t terraformoutput.json`,
+		Example:       `kubeone kubeconfig -m mycluster.yaml -t terraformoutput.json`,
+		SilenceErrors: true,
```
Comment (xmudrii) [inline pkg/cmd/kubeconfig.go:42]: What is this option used for?

Comment (kron4eg) [reply pkg/cmd/kubeconfig.go:42]: When it's set to default (by default), cobra will automatically report errors. And then we report error, it's the same error printed out two times.

```
        // inside the cobra
	if err != nil {
		// If found parse to a subcommand and then failed, talk about the subcommand
		if cmd != nil {
			c = cmd
		}
		if !c.SilenceErrors {
			c.PrintErrln("Error:", err.Error())
			c.PrintErrf("Run '%v --help' for usage.\n", c.CommandPath())
		}
		return c, err
	}
```

Comment (kron4eg) [reply pkg/cmd/kubeconfig.go:42]: However I want to control the way to output so I had to `SilenceErrors: true`, to skip automatic print.

**Review by xmudrii — APPROVED** [review]
