### PR TITLE
Delete worker nodes using dynamic client and add an option to remove Kubernetes packages when resetting the cluster

### LINKED ISSUE #397: Reset doesn't remove Kubernetes binaries
**What happened**:

`kubeone reset` doesn't remove Kubernetes binaries (kubeadm, kubelet..).

**What is the expected behavior**:

Kubernetes binaries are removed from the instances.

**How to reproduce the issue**:

Run `kubeone reset` and verify are `kubeadm` and `kubelet` installed.

**Anything else we need to know?**

This makes it impossible to install the older Kubernetes version, as the `kubelet` binary is newer.

### LINKED ISSUE #447: error: the server doesn't have a resource type "machinedeployment"
**What happened**:
I tried to delete a cluster with the following config:

```
apiVersion: kubeone.io/v1alpha1
kind: KubeOneCluster
name: demo
versions:
  kubernetes: "1.13.2"
cloudProvider:
  name: "none"
hosts:
- publicAddress: '1.2.3.4'
  privateAddress: '172.18.0.1'
  sshPort: 22 # can be left out if using the default (22)
  sshUsername: ubuntu
machineController:
  deploy: false
  provider: "none"
```

This failed with the following issue:
```
~/go/bin/kubeone reset config.yaml -v
INFO[08:22:07 CEST] Resetting kubeadm…
INFO[08:22:07 CEST] Destroying worker nodes…                      node=172.18.0.1
+ kubectl cluster-info
+ 1> /dev/null
+ kubectl annotate --all --overwrite node 'kubermatic.io/skip-eviction=true'
node/master0 annotated
+ kubectl delete machinedeployment -n kube-system --all
error: the server doesn't have a resource type "machinedeployment"
Error: failed to exec command: export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"

set -xeu pipefail


if kubectl cluster-info > /dev/null; then
  kubectl annotate --all --overwrite node kubermatic.io/skip-eviction=true
  kubectl delete machinedeployment -n "kube-system" --all
  kubectl delete machineset -n "kube-system" --all
  kubectl delete machine -n "kube-system" --all

  for try in {1..30}; do
    if kubectl get machine -n "kube-system" 2>&1 | grep -q  'No resources found.'; then
      exit 0
    fi
    sleep 10s
  done

  echo "Error: Couldn't delete all machines!"
  exit 1
fi
: Process exited with status 1
```

**What is the expected behavior**:
Deletion proceeds.

**How to reproduce the issue**:
Try to delete a cluster when the following is set in config.yaml
```
machineController:
  deploy: false
  provider: "none"
```

**Anything else we need to know?**

**Information about the environment**:
KubeOne version (kubeone version): v0.6.0-6-g6407139
Operating system: CentOS Linux release 7.6.1810 (Core)
Provider you're deploying cluster on: Bare-metal
Operating system you're deploying on: CentOS Linux release 7.6.1810 (Core)

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

This PR refactors the `reset` command to use dynamic client instead of kubectl over SSH tunnel for deleting worker nodes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #447 
Fixes #397

**Release note**:
```release-note
Fix reset failures if there are no Machine objects or Cluster-API CRDs are not deployed
Add the --remove-binaries flag which removes Kubernetes binaries after resetting the cluster
```

/assign @kron4eg

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -67,7 +66,7 @@ docker-make-install:
 		make install
 
 .PHONY: e2e_test
-e2e_test:
+e2e_test: build lint test dep
```
Comment (kron4eg) [inline Makefile]: `s/dep/check-dependencies/` — we'd like to know when deps are updated but not checked-in
also add `licence-check` to this step.

**Comment by xmudrii** [comment]
This is a `yamled` flake.
/retest

File: pkg/templates/machinecontroller/helper.go [hunk 2]
```diff
@@ -75,3 +79,80 @@ func WaitReady(ctx *util.Context) error {
...
+	nodes := &corev1.NodeList{}
+	if err := ctx.DynamicClient.List(bgCtx, &dynclient.ListOptions{}, nodes); err != nil {
+		return errors.Wrap(err, "unable to list nodes")
+	}
+	for i := range nodes.Items {
+		if nodes.Items[i].Annotations == nil {
+			nodes.Items[i].Annotations = map[string]string{}
+		}
+		nodes.Items[i].Annotations["kubermatic.io/skip-eviction"] = "true"
+		if err := ctx.DynamicClient.Update(bgCtx, &nodes.Items[i]); err != nil {
```
Comment (kron4eg) [inline pkg/templates/machinecontroller/helper.go]: This is part should contain retry logic, as it's likely that you'll hit a conflict. There is `k8s.io/client-go/util/retry` helper package for retries.

File: Makefile (hunk 1 above)
Comment (kron4eg) [reply Makefile]: OK, probably no `licence-check`, sorry, it's different image.

File: pkg/templates/machinecontroller/helper.go (hunk 2 above)
Comment (xmudrii) [reply pkg/templates/machinecontroller/helper.go]: Check now. :)

File: Makefile (hunk 1 above)
Comment (xmudrii) [reply Makefile]: Regarding changing `dep` to checking `check-dependencies`, it would require a change to the presubmit, so let's leave it for a follow-up.

**Comment by xmudrii** [comment]
/hold
I'll take care of #397 as well

**Comment by xmudrii** [comment]
/hold
This is a second flake related to reset not being able to delete the MachineSet. It should be fixed before merging the PR.

File: pkg/cmd/reset.go [hunk 3]
```diff
@@ -63,6 +64,7 @@ It's possible to source information about hosts from Terraform output, using the
 	}
 
 	cmd.Flags().BoolVarP(&ropts.DestroyWorkers, "destroy-workers", "", true, "destroy all worker machines before resetting the cluster")
+	cmd.Flags().BoolVarP(&ropts.RemovePackages, "remove-packages", "", false, "remove kubernetes packages after resetting the cluster")
```
Comment (xmudrii) [inline pkg/cmd/reset.go]: I'm concerned about the flag name. Packages may be a bad word here because we don't use package management solution on all platforms. For example, on CoreOS we download and install binaries manually. Technically, `remove-binaries` could work better. Any opinions?

Comment (kron4eg) [reply pkg/cmd/reset.go]: `remove-binaries` sgtm

Comment (xmudrii) [reply pkg/cmd/reset.go]: Done. :100:
