### PR TITLE
ignore +suffix when parsing kernel versions

### LINKED ISSUE #4008: kubeone apply fails on kernels with '+' in the version
### What happened?

`kubeone apply` fails on Debian when a kernel contains a '+'. 

```
INFO[19:58:25 CET] Running host probes...
ERRO[19:58:25 CET] runtime: parsing kernel release version: "6.12.74+deb13+1-amd64"
Invalid Semantic Version  node=*redacted*
```

### Expected behavior

`kubeone` should not fail.

### How to reproduce the issue?

The latest kernel in Debian Trixie is 6.12.74+deb13+1-amd64 and triggers the issue.

### What KubeOne version are you using?

<details>

```console
$ kubeone version
{
  "kubeone": {
    "major": "1",
    "minor": "12",
    "gitVersion": "1.12.3",
    "gitCommit": "none",
    "gitTreeState": "",
    "buildDate": "2026-01-22T16:15:08Z",
    "goVersion": "go1.25.6",
    "compiler": "gc",
    "platform": "darwin/arm64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "64",
    "gitVersion": "v1.64.0",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}```

</details>


### What cloud provider are you running on?

baremetal

### What operating system are you running in your cluster?

Debian Trixie

### PR DESCRIPTION
**Pull request by ttuellmann**
**What this PR does / why we need it**:

Strip '+suffix' from kernel versions when parsing the kernel's semantic version.

**Which issue(s) this PR fixes**:

Fixes #4008 

**What type of PR is this?**

/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Strip '+suffix' from kernel versions when parsing the kernel's semantic version.
```

**Documentation**:

```
NONE
```

### CODE REVIEW

File: pkg/tasks/probes.go [hunk 1]
```diff
@@ -475,6 +475,7 @@ func investigateHost(s *state.State, node *kubeoneapi.HostConfig, conn executor.
 
 func kernelSemver(krelease string) (*semver.Version, error) {
 	kver := strings.SplitN(krelease, "-", 2)[0]
+	kver = strings.SplitN(kver, "+", 2)[0]
```
Comment (kron4eg) [inline pkg/tasks/probes.go:478]: can you please add some unit-tests

Comment (ttuellmann) [reply pkg/tasks/probes.go:478]: Something like 4a65ea71cabe53604db4d76e39210ea020197e55 ?

Comment (kron4eg) [reply pkg/tasks/probes.go:478]: exactly, just please the linter issue

**Comment by ttuellmann** [comment]
This should pass the linter.

**Comment by ttuellmann** [comment]
Sorry for the mess. Your workflow and your bot are a bit over my head.

**Comment by ttuellmann** [comment]
@kron4eg The test is trying to install 1.35.3, which is not in https://pkgs.k8s.io/core:/stable:/v1.35/deb/Packages . And it does not look like it is even released yet.

**Comment by kron4eg** [comment]
@ttuellmann yeah, lucky timing :) kubernetes tagged a new version but didn't delivered yet a new binaries. Let's give them time to build.

**Comment by kron4eg** [comment]
@ttuellmann thank you for your contribution!

**Comment by ttuellmann** [comment]
Glad this was helpful!
