### PR TITLE
Use systemd cgroups driver on CoreOS and enable kubelet by default

### LINKED ISSUE #363: WARNING IsDockerSystemdCheck
**What happened**:
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/

**What is the expected behavior**:
No IsDockerSystemdCheck warning

**How to reproduce the issue**:
`kubeone install -v`

**Information about the environment**:
KubeOne version (`kubeone version`): master (as of today)
Operating system: macos
Provider you're deploying cluster on: hetzner
Operating system you're deploying on: ubuntu

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

This PR configures Docker on CoreOS to use `systemd` as a cgroups manager and `overlay2` as a storage driver. The installation script for CoreOS will now short-circuit if Docker and Kubelet are already present, like on Ubuntu and CentOS.

Lastly, Kubelet service is now enabled by default on Ubuntu and CentOS (it is already done on CoreOS). On Ubuntu it should have been like this by default, but not on CoreOS, causing `kubeadm` to complain.

Note that CoreOS still has 2 warnings that should be resolved, but those are not related to the `IsDockerSystemdCheck` warning.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #363 

**Does this PR introduce a user-facing change?**:
```release-note
Fix kubeadm warnings on CentOS and CoreOS
```

/assign @kron4eg

### CODE REVIEW

File: pkg/installer/installation/prerequisites.go [hunk 1]
```diff
@@ -167,11 +168,24 @@ sudo yum install -y --disableexcludes=kubernetes \
...
 	kubernetes-cni-{{ .CNI_VERSION }}-0
 sudo systemctl enable --now docker
+sudo systemctl enable --now kubelet
 `
 
 	kubeadmCoreOSScript = `
 source /etc/kubeone/proxy-env
 
+# Short-Circuit the installation if it was already executed
+if type docker &>/dev/null && type kubelet &>/dev/null; then exit 0; fi
```
Comment (kron4eg) [inline pkg/installer/installation/prerequisites.go]: nope, that shouldn't be here

Comment (xmudrii) [reply pkg/installer/installation/prerequisites.go]: Why? Isn't `kubeone install` if run multiple times always going to reinstall kubelet? Don't we want to prevent that?

Comment (kron4eg) [reply pkg/installer/installation/prerequisites.go]: oh well, yes, I didn't paid attention to what followed change lines (and was hidden).
