### PR TITLE
Generate and approve CSRs for conntrol-plane and static workers nodes

### LINKED ISSUE #1093: Kubelets on Control Plane hosts serve a invalid certificate with configuration defaults
**What happened**:
The Kubelet endpoint (port 10250) on Control Plane nodes serve a certificate on https that results in `x509: certificate signed by unknown authority` errors. (This error is not occurring on worker nodes provisioned by the MachineController.)

**What is the expected behavior**:
The Kubelet endpoint should serve a valid certificate.

**How to reproduce the issue**:
Provision a new cluster with KubeOne, and then create a Pod running on one of the Control Plane nodes with curl. In the Pod spec, set an environment variable `DD_KUBERNETES_KUBELET_HOST` to use a valueFrom set to the fieldRef `spec.nodeName`. Gain a shell inside the pod and run:
```bash
curl https://$DD_KUBERNETES_KUBELET_HOST:10250/pods -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(</var/run/secrets/kubernetes.io/serviceaccount/token)"
```

curl should report a `SSL certificate problem: self signed certificate in certificate chain` error message 

**Anything else we need to know?**
We asked about the issue in the #kubeone channel on the K8s Slack, and a engineer suggested setting the following value in the `/var/lib/kubelet/config.yaml` file on our Control Plane host:
```yaml
serverTLSBootstrap: true
```

After adding that value and restarting the kubelet on the affected host, a CSR was made in the Kubernetes API. We approved the CSR, and the kubelet endpoint started served a valid certificate without the self-signed errors.

Link to the suggestion: [Slack](https://kubernetes.slack.com/archives/CNEV2UMT7/p1599050012052500)

**Information about the environment**:
KubeOne version (`kubeone version`): 1.0.1
Operating system: macOS
Provider you're deploying cluster on: AWS
Operating system you're deploying on: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
Fixes the issue that kubelets on control-plane and static workers nodes are service requests under self-signed certificates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1093

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Generate and approve CSRs for conntrol-plane and static workers nodes
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
Great work

/lgtm
/approve

File: pkg/tasks/certs.go [hunk 1]
```diff
@@ -158,3 +180,108 @@ func saveCABundleOnControlPlane(s *state.State, _ *kubeoneapi.HostConfig, conn s
 	_, _, err = s.Runner.RunRaw(cmd)
 	return err
 }
+
+func approvePendingCSR(s *state.State, node *kubeoneapi.HostConfig, conn ssh.Connection) error {
+	s.Logger.Infof("Looking for CSRs to approve...")
+
+	// Need to wait for the second CSR to appear
+	time.Sleep(20 * time.Second)
```
Comment (xmudrii) [inline pkg/tasks/certs.go:188]: I think we should leave a log message that KubeOne is waiting 20 seconds for CSRs to appear. We already do that when we wait for other tasks (e.g. for the control plane instance to come up).

File: pkg/tasks/certs.go [hunk 2]
```diff
@@ -158,3 +180,108 @@ func saveCABundleOnControlPlane(s *state.State, _ *kubeoneapi.HostConfig, conn s
...
+
+	if !sets.NewString(spec.Groups...).HasAll(groupNodes, groupAuthenticated) {
+		return errors.New("")
+	}
+
+	for _, usage := range spec.Usages {
+		if !isUsageInUsageList(usage, allowedUsages) {
+			return errors.New("")
+		}
+	}
```
Comment (xmudrii) [inline pkg/tasks/certs.go:249]: Why is this returning empty errors?

File: pkg/tasks/certs.go [hunk 3]
```diff
@@ -158,3 +180,108 @@ func saveCABundleOnControlPlane(s *state.State, _ *kubeoneapi.HostConfig, conn s
...
+
+	csrBlock, rest := pem.Decode(spec.Request)
+	if csrBlock == nil {
+		return fmt.Errorf("no certificate request found for the given CSR")
+	}
+
+	if len(rest) != 0 {
+		return fmt.Errorf("found more than one PEM encoded block in the result")
+	}
```
Comment (xmudrii) [inline pkg/tasks/certs.go:258]: Why don't we use `errors.New()` here?

**Review by xmudrii — COMMENTED** [review]
Retroactive reveiw.
